### ISSUE TITLE
Testing POST.Dose for production release

### ISSUE THREAD

**Issue by eak24** [AguaClara/post.dose#3]
@asm278 So cool to see this working! So many parts to connect. 

First thought is can you make the model parameters available through an API that you don't need a gmail account to access? It's very confusing that I need to select an account just to get a coag dose recommendation. 

Also, am I supposed to be getting a real value? right now when I open the dose app and get the sheets values, I get all 0s... But when I look at the spreadsheet, it's populated with a bunch of values. 

Finally, although I'm ok shipping this without being plant specific, in the future we need to make this plant specific, meaning there is a different model for each plant, and when the ODK form opens the intent, it feeds the plant name into the app to get those particular plant parameters. Other things to think about are how to handle the first time that a plant submits data... maybe in that case, we should fall back on parameters calculated for the average of all plants. 

When we update the form to call this, make sure to work closely with Jay, I suggest forking the post.OdkForms repo with a coag dose recommendation branch. 

Thanks!!

**Comment by asm278** [comment]
I have found the issue with the keys that prevents post.aguaclara from accessing the sheet, now I need to track down which project already has the key in use. I'll post here again once its resolved.

I don't know why Google APIs insist on having a login to access a public google sheet, and I don't really know of any other good APIs to use (apart from making our own server...)

I didn't know that we were doing this in a plant-specific way. I can start to swap it over to being plant-specific -- any suggestions on where to make the general/specific model cutoff ?  I imagine that even after the third time that a plant uploads data, the general model would be better than a plant specific one. 

I will branch odkforms

**Comment by asm278** [comment]
I have the model retrieval working on my emulator now.
